services:
  app:
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    build:
      context: ./node
    volumes:
      - ./node:/usr/app
    networks:
      - node-net
    tty: true
  nginx:
    image: nginx
    ports:
      - "8080:80"
    build:
      context: ./nginx
    volumes:
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - node-net
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: nodedb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - node-net

networks:
    node-net: